/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.memorygamev2.Interface;
import com.mycompany.memorygamev2.Game;
import com.mycompany.memorygamev2.IA;
import java.awt.Color;
import java.util.Stack;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author vinic
 */
public class PlayerXPlayer extends javax.swing.JFrame {
    Game game = new Game(4);
    int player1 = 0;
    int player2 = 0;
    boolean ativ = false;
    int[] coords = {-1, -1, -1, -1};
    IA bot = new IA(4);
    int v = 1;
    Stack<javax.swing.JButton> stack = new Stack<javax.swing.JButton>();
    ImageIcon imageBack = new ImageIcon("src\\main\\java\\Image\\Captura de tela 2024-12-03 002323.png");
    ImageIcon[] vecImages = new ImageIcon[8];
    
    boolean verify(int l, int m){
        if(!ativ){
            coords[0] = l;
            coords[1] = m;
        }
        
        else {
            coords[2] = l;
            coords[3] = m;
            return game.play(bot, coords);
        }
        
        return false;
    }
    
    public void construo(){
        for(int i = 0; i < 8; ++i){
            String aux = "src\\main\\java\\Image\\image";
            aux += String.valueOf(i + 1) + ".jpg";
            vecImages[i] = new ImageIcon(aux);
            Image Resizer = vecImages[i].getImage().getScaledInstance(150, 201, Image.SCALE_SMOOTH);
            vecImages[i] = new ImageIcon(Resizer);
        }
    }
    
    /**
     * Creates new form PlayerXPlayer
     */
    public PlayerXPlayer() {
        initComponents();
        Image image = imageBack.getImage().getScaledInstance(150, 201, Image.SCALE_SMOOTH);
        imageBack = new ImageIcon(image);
        jButton1.setIcon(imageBack);
        jButton10.setIcon(imageBack);
        jButton11.setIcon(imageBack);
        jButton12.setIcon(imageBack);
        jButton13.setIcon(imageBack);
        jButton14.setIcon(imageBack);
        jButton15.setIcon(imageBack);
        jButton16.setIcon(imageBack);
        jButton2.setIcon(imageBack);
        jButton3.setIcon(imageBack);
        jButton4.setIcon(imageBack);
        jButton5.setIcon(imageBack);
        jButton6.setIcon(imageBack);
        jButton7.setIcon(imageBack);
        jButton8.setIcon(imageBack);
        jButton9.setIcon(imageBack);
        
        construo();
        game.Gen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        popupMenu1 = new java.awt.PopupMenu();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        P1Points = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        P1 = new javax.swing.JLabel();
        P2Points = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("jButton1");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("jButton1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("jButton1");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("jButton1");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("jButton1");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("jButton1");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("jButton1");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("jButton1");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("jButton1");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ryōiki Tenkai: Mugen no memori");

        P1Points.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        P1Points.setForeground(new java.awt.Color(255, 255, 255));
        P1Points.setText("0");

        P2.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        P2.setForeground(new java.awt.Color(255, 255, 255));
        P2.setText("Player2:");

        P1.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        P1.setForeground(new java.awt.Color(255, 0, 51));
        P1.setText("Player1:");

        P2Points.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        P2Points.setForeground(new java.awt.Color(255, 255, 255));
        P2Points.setText("0");

        jButton17.setText("Break");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(P2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(P1Points)
                                .addGap(300, 300, 300)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(343, 343, 343)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(P2Points)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(595, 595, 595)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(P1)
                    .addContainerGap(945, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(58, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(P1Points)
                        .addGap(127, 127, 127)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P2)
                            .addComponent(P2Points))
                        .addGap(347, 347, 347))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(343, 343, 343)
                    .addComponent(P1)
                    .addContainerGap(519, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!game.getBoolean(0, 0) && (player1 + player2) < (((4 * 4) / 2))){
            jButton2.setIcon(vecImages[game.getInt(0, 0)]);
            boolean match = verify(0,0);
            if(!ativ){
                ativ = true;
                stack.add(jButton2);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton2.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!game.getBoolean(0, 1) && (player1 + player2) < (((4 * 4) / 2))){
            jButton1.setIcon(vecImages[game.getInt(0, 1)]);
            boolean match = verify(0, 1);
            if(!ativ){
                ativ = true;
                stack.add(jButton1);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton1.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(!game.getBoolean(0, 2) && (player1 + player2) < (((4 * 4) / 2))){
            jButton4.setIcon(vecImages[game.getInt(0, 2)]);
            boolean match = verify(0,2);
            if(!ativ){
                ativ = true;
                stack.add(jButton4);
            }
            
            else {
                ativ = false;
                if(!match){
                    
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton4.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!game.getBoolean(0, 3) && (player1 + player2) < (((4 * 4) / 2))){
            jButton3.setIcon(vecImages[game.getInt(0, 3)]);
            boolean match = verify(0,3);
            if(!ativ){
                ativ = true;
                stack.add(jButton3);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton3.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(!game.getBoolean(1, 0) && (player1 + player2) < (((4 * 4) / 2))){
            jButton8.setIcon(vecImages[game.getInt(1, 0)]);
            boolean match = verify(1,0);
            if(!ativ){
                ativ = true;
                stack.add(jButton8);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton8.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(!game.getBoolean(1, 1) && (player1 + player2) < (((4 * 4) / 2))){
            jButton7.setIcon(vecImages[game.getInt(1, 1)]);
            boolean match = verify(1,1);
            if(!ativ){
                ativ = true;
                stack.add(jButton7);
            }
            
            else {
                ativ = false;
                if(!match){
                   Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton7.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(!game.getBoolean(1, 2) && (player1 + player2) < (((4 * 4) / 2))){
            jButton6.setIcon(vecImages[game.getInt(1, 2)]);
            boolean match = verify(1, 2);
            if(!ativ){
                ativ = true;
                stack.add(jButton6);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton6.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(!game.getBoolean(1, 3) && (player1 + player2) < (((4 * 4) / 2))){
            jButton5.setIcon(vecImages[game.getInt(1, 3)]);
            boolean match = verify(1, 3);
            if(!ativ){
                ativ = true;
                stack.add(jButton5);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton5.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(!game.getBoolean(2, 0) && (player1 + player2) < (((4 * 4) / 2))){
            jButton11.setIcon(vecImages[game.getInt(2, 0)]);
            boolean match = verify(2,0);
            if(!ativ){
                ativ = true;
                stack.add(jButton11);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton11.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if(!game.getBoolean(2, 1) && (player1 + player2) < (((4 * 4) / 2))){
            jButton12.setIcon(vecImages[game.getInt(2, 1)]);
            boolean match = verify(2, 1);
            if(!ativ){
                ativ = true;
                stack.add(jButton12);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton12.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(!game.getBoolean(2, 2) && (player1 + player2) < (((4 * 4) / 2))){
            jButton10.setIcon(vecImages[game.getInt(2, 2)]);
            boolean match = verify(2,2);
            if(!ativ){
                ativ = true;
                stack.add(jButton10);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton10.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(!game.getBoolean(2, 3) && (player1 + player2) < (((4 * 4) / 2))){
            jButton9.setIcon(vecImages[game.getInt(2, 3)]);
            boolean match = verify(2,3);
            if(!ativ){
                ativ = true;
                stack.add(jButton9);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton9.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if(!game.getBoolean(3, 0) && (player1 + player2) < (((4 * 4) / 2))){
            jButton15.setIcon(vecImages[game.getInt(3, 0)]);
            boolean match = verify(3,0);
            if(!ativ){
                ativ = true;
                stack.add(jButton15);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton15.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if(!game.getBoolean(3, 1) && (player1 + player2) < (((4 * 4) / 2))){
            jButton16.setIcon(vecImages[game.getInt(3, 1)]);
            boolean match = verify(3, 1);
            if(!ativ){
                ativ = true;
                stack.add(jButton16);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton16.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if(!game.getBoolean(3, 2) && (player1 + player2) < (((4 * 4) / 2))){
            jButton14.setIcon(vecImages[game.getInt(3, 2)]);
            boolean match = verify(3,2);
            if(!ativ){
                ativ = true;
                stack.add(jButton14);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton14.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        }
                        else {
                            P1.setForeground(Color.white);
                            P2.setForeground(Color.magenta);
                        }
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if(!game.getBoolean(3, 3) && (player1 + player2) < (((4 * 4) / 2))){
            jButton13.setIcon(vecImages[game.getInt(3, 3)]);
            boolean match = verify(3, 3);
            if(!ativ){
                ativ = true;
                stack.add(jButton13);
            }
            
            else {
                ativ = false;
                if(!match){
                    Timer delayTimer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        stack.pop().setIcon(imageBack);
                        jButton13.setIcon(imageBack);
                        v++;
                        if(v % 2 != 0) {
                            P1.setForeground(Color.red);
                            P2.setForeground(Color.white);
                        } 
                    }
                    });
                    delayTimer.setRepeats(false);
                    delayTimer.start();
                }
                
                else{
                    stack.pop();
                    if(v % 2 != 0){
                        player1++;
                        P1Points.setText(String.valueOf(player1));
                    }
                    else { 
                        player2++;
                        P2Points.setText(String.valueOf(player2));
                    }
                }
            }
        }
        
        else {
            this.setVisible(false);
            if(v % 2 != 0)JOptionPane.showMessageDialog(null,"Gojo Wins");
            else JOptionPane.showMessageDialog(null,"Sukuna Wins");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        this.setVisible(false);
        Initialization console = new Initialization();
        console.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerXPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerXPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerXPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerXPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerXPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P1Points;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P2Points;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
